# Generated by Django 5.0.6 on 2025-07-26 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del evento')),
                ('fecha_evento', models.DateTimeField(verbose_name='Fecha y hora del evento')),
                ('lugar', models.CharField(max_length=300, verbose_name='Lugar del evento')),
                ('es_festivo', models.BooleanField(default=False, verbose_name='¿Es festivo?')),
                ('responsable', models.CharField(max_length=200, verbose_name='Responsable del evento o persona que invita')),
                ('asistio_gobernador', models.BooleanField(default=True, verbose_name='¿Asistió el Gobernador?')),
                ('representante', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del representante (si no asistió el Gobernador)')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del evento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-fecha_evento'],
            },
        ),
    ]
