# Generated by Django 5.0.6 on 2025-07-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.CharField(choices=[('programado', 'Programado'), ('en_curso', 'En Curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado del evento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_finalizacion_manual',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización manual'),
        ),
    ]
